apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: tomcat
          image: harmson/containerapp
          ports:
          - name: app-port
            containerPort: 8080
        
      initContainers:
        - name: init-db
          image: busybox:latest
          args: ["sh", "-c", "until nslookup vprodb; do echo wating for my db; donme;"]
        - name: init-memcached
          image: busybox:latest
          args: ["sh", "-c", "until nslookup vprocache01; do echo wating for my db; donme;"]        
